name: NPM发布

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: '版本更新类型 (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: 设置Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: 安装依赖
        run: npm ci
      
      - name: 更新版本号
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 获取当前版本
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "当前版本: $CURRENT_VERSION"
          
          # 手动计算下一个版本号
          VERSION_TYPE="${{ github.event.inputs.version_type }}"
          IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
          MAJOR=${version_parts[0]}
          MINOR=${version_parts[1]}
          PATCH=${version_parts[2]}
          
          if [ "$VERSION_TYPE" = "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "$VERSION_TYPE" = "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi
          
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "新版本: $NEW_VERSION"
          
          # 直接修改 package.json
          sed -i "s/\"version\": \"$CURRENT_VERSION\"/\"version\": \"$NEW_VERSION\"/" package.json
          
          # 提交更改
          git status
          git add package.json
          git commit -m "版本更新到 v$NEW_VERSION"
          
          # 添加标签
          git tag -a "v$NEW_VERSION" -m "v$NEW_VERSION"
          
          # 推送更改
          git push
          git push --tags
      
      - name: 构建项目
        run: npm run build
      
      - name: 登录到NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm whoami || echo "NPM 登录失败，但继续执行"
      
      - name: 发布到NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 