name: NPM发布

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: '版本更新类型'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch   # 补丁版本: 1.0.0 -> 1.0.1
          - minor   # 次要版本: 1.0.0 -> 1.1.0
          - major   # 主要版本: 1.0.0 -> 2.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: 安装依赖
        run: npm ci
      
      - name: 更新版本
        id: version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # 获取当前版本
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "当前版本: $CURRENT_VERSION"
          
          # 更新版本
          npm version ${{ github.event.inputs.version_type }}
          
          # 获取新版本
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "新版本: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          git push
          git push --tags
      
      - name: 构建项目
        run: npm run build
      
      - name: 发布到NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
      
      - name: 发布结果
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "包已发布！"
          echo "版本: ${{ steps.version.outputs.version }}"
          echo "类型: ${{ steps.publish.outputs.type }}"
          echo "URL: https://www.npmjs.com/package/@sz/sherry-cli/v/${{ steps.version.outputs.version }}"
