name: NPM发布

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: '版本更新类型'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch   # 补丁版本: 1.0.0 -> 1.0.1
          - minor   # 次要版本: 1.0.0 -> 1.1.0
          - major   # 主要版本: 1.0.0 -> 2.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: 配置Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: 安装依赖
        run: npm ci
      
      - name: 更新版本
        run: |
          echo "更新版本类型: ${{ github.event.inputs.version_type }}"
          npm version ${{ github.event.inputs.version_type }} -m "版本更新 %s"
          git push
          git push --tags
      
      - name: 构建
        run: npm run build
      
      - name: 配置NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: 创建或更新组织
        run: |
          if ! npm org ls sz &>/dev/null; then
            echo "创建组织 sz"
            npm org create sz || true
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: 发布到NPM
        run: |
          npm publish --access public || npm publish --access public --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
